# Generated by Django 3.0.2 on 2020-07-20 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Movies', '0002_newtrailer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newtrailer',
            name='discription',
            field=models.TextField(max_length=5000),
        ),
    ]
