# Generated by Django 3.0.2 on 2020-07-20 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Movies', '0004_newtrailer_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newtrailer',
            name='discription',
            field=models.TextField(blank=True, max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name='newtrailer',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='trailer_image'),
        ),
        migrations.AlterField(
            model_name='newtrailer',
            name='link',
            field=models.CharField(blank=True, max_length=1500, null=True),
        ),
        migrations.AlterField(
            model_name='newtrailer',
            name='title',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
