# Generated by Django 3.0.2 on 2020-07-21 07:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Movies', '0008_auto_20200721_1243'),
    ]

    operations = [
        migrations.CreateModel(
            name='season',
            fields=[
                ('series', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='Movies.SeriesModel')),
                ('image', models.ImageField(blank=True, null=True, upload_to='seasons/')),
                ('trailer', models.CharField(blank=True, max_length=5000, null=True)),
                ('link1', models.CharField(blank=True, max_length=5000, null=True)),
                ('link2', models.CharField(blank=True, max_length=5000, null=True)),
                ('link3', models.CharField(blank=True, max_length=5000, null=True)),
                ('online_link', models.CharField(blank=True, max_length=5000, null=True)),
                ('id', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
