# Generated by Django 3.0.2 on 2020-07-21 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Movies', '0009_season'),
    ]

    operations = [
        migrations.AddField(
            model_name='season',
            name='episode',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='season',
            name='selected_season',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
