# Generated by Django 3.0.2 on 2020-07-25 12:59

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Movies', '0010_auto_20200721_1332'),
    ]

    operations = [
        migrations.AddField(
            model_name='movies',
            name='qulity_4k',
            field=models.CharField(default=django.utils.timezone.now, max_length=10),
            preserve_default=False,
        ),
    ]
