# Generated by Django 3.0.2 on 2020-07-25 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Movies', '0011_movies_qulity_4k'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movies',
            name='qulity_4k',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
