# Generated by Django 3.0.2 on 2020-07-26 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Movies', '0012_auto_20200725_1839'),
    ]

    operations = [
        migrations.AddField(
            model_name='movies',
            name='background_image_link',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='movies',
            name='thumbnail_link',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
