# Generated by Django 3.0.2 on 2020-07-26 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Movies', '0013_auto_20200726_1012'),
    ]

    operations = [
        migrations.AddField(
            model_name='movies',
            name='screen_shot_link',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='newtrailer',
            name='image_link',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
