# Generated by Django 3.0.2 on 2020-07-26 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Movies', '0014_auto_20200726_1015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movies',
            name='release_date',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
