# Generated by Django 3.0.2 on 2020-07-26 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Movies', '0016_auto_20200726_1115'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movies',
            name='torent_link',
        ),
        migrations.AddField(
            model_name='movies',
            name='torent_link_1920',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='movies',
            name='torent_link_4k',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='movies',
            name='torent_link_720',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='movies',
            name='torent_file_link',
            field=models.FileField(blank=True, null=True, upload_to='torent_movie'),
        ),
    ]
