# Generated by Django 3.0.2 on 2020-07-26 05:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Movies', '0017_auto_20200726_1118'),
    ]

    operations = [
        migrations.AddField(
            model_name='movies',
            name='slug',
            field=models.SlugField(default=django.utils.timezone.now, max_length=500),
            preserve_default=False,
        ),
    ]
