# Generated by Django 3.0.2 on 2020-07-26 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Movies', '0018_movies_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movies',
            name='movie_subscription',
        ),
        migrations.AddField(
            model_name='movies',
            name='premium',
            field=models.BooleanField(default=False),
        ),
    ]
