# Generated by Django 3.0.2 on 2020-07-26 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Movies', '0019_auto_20200726_1122'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movies',
            name='movie_quality',
        ),
        migrations.RemoveField(
            model_name='movies',
            name='movie_size',
        ),
        migrations.AddField(
            model_name='movies',
            name='size_1920',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='movies',
            name='size_4k',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='movies',
            name='size_720',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
